n = str(input('Digite seu nome completo: ')).strip()
nome = n.strip()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(nome[0]))
print('Seu último nome pe {}'.format(nome[len(nome)-1]))